package org.mirror.DTO.quoteSummary.moduleInfo;

import lombok.Data;
import org.mirror.DTO.quoteSummary.moduleInfo.balanceSheetHistoryQuarterly.BalanceSheetHistoryQuarterly;
import org.mirror.DTO.quoteSummary.moduleInfo.calendatEvents.CalendarEvents;
import org.mirror.DTO.quoteSummary.moduleInfo.cashFlowStatementHistoryQuarterly.CashFlowStatementHistoryQuarterly;
import org.mirror.DTO.quoteSummary.moduleInfo.finanacialData.FinancialData;
import org.mirror.DTO.quoteSummary.moduleInfo.futuresChain.FuturesChain;
import org.mirror.DTO.quoteSummary.moduleInfo.incomeStatementHistoryQuarterly.IncomeStatementHistoryQuarterly;
import org.mirror.DTO.quoteSummary.moduleInfo.industryTrend.IndustryTrend;
import org.mirror.DTO.quoteSummary.moduleInfo.majorDirectHolders.MajorDirectHolders;
import org.mirror.DTO.quoteSummary.moduleInfo.sectorTrend.SectorTrend;
import org.mirror.consts.QuoteSummaryModuleConsts;
import org.mirror.gernerator.ModuleWrapperGenerator;

import org.mirror.DTO.quoteSummary.moduleInfo.summaryProfile.SummaryProfile;
import org.mirror.DTO.quoteSummary.moduleInfo.summaryDetail.SummaryDetail;
import org.mirror.DTO.quoteSummary.moduleInfo.assetProfile.AssetProfile;
import org.mirror.DTO.quoteSummary.moduleInfo.fundProfile.FundProfile;
import org.mirror.DTO.quoteSummary.moduleInfo.price.Price;
import org.mirror.DTO.quoteSummary.moduleInfo.quoteType.QuoteType;
import org.mirror.DTO.quoteSummary.moduleInfo.esgScores.EsgScores;
import org.mirror.DTO.quoteSummary.moduleInfo.incomeStatementHistory.IncomeStatementHistory;
import org.mirror.DTO.quoteSummary.moduleInfo.balanceSheetHistory.BalanceSheetHistory;
import org.mirror.DTO.quoteSummary.moduleInfo.cashFlowStatementHistory.CashFlowStatementHistory;
import org.mirror.DTO.quoteSummary.moduleInfo.defaultKeyStatistics.DefaultKeyStatistics;
import org.mirror.DTO.quoteSummary.moduleInfo.secFilings.SecFilings;
import org.mirror.DTO.quoteSummary.moduleInfo.upgradeDowngradeHistory.UpgradeDowngradeHistory;
import org.mirror.DTO.quoteSummary.moduleInfo.institutionOwnership.InstitutionOwnership;
import org.mirror.DTO.quoteSummary.moduleInfo.fundOwnership.FundOwnership;
import org.mirror.DTO.quoteSummary.moduleInfo.majorHoldersBreakdown.MajorHoldersBreakdown;
import org.mirror.DTO.quoteSummary.moduleInfo.insiderTransactions.InsiderTransactions;
import org.mirror.DTO.quoteSummary.moduleInfo.insiderHolders.InsiderHolders;
import org.mirror.DTO.quoteSummary.moduleInfo.netSharePurchaseActivity.NetSharePurchaseActivity;
import org.mirror.DTO.quoteSummary.moduleInfo.earnings.Earnings;
import org.mirror.DTO.quoteSummary.moduleInfo.earningsHistory.EarningsHistory;
import org.mirror.DTO.quoteSummary.moduleInfo.earningsTrend.EarningsTrend;
import org.mirror.DTO.quoteSummary.moduleInfo.indexTrend.IndexTrend;
import org.mirror.DTO.quoteSummary.moduleInfo.recommendationTrend.RecommendationTrend;

/**
 * Contains all the possible ModuleInfo object that can be grabbed from Yahoo.
 * <p>
 * All member variables are generated by {@link ModuleWrapperGenerator} according to {@link QuoteSummaryModuleConsts}
 */
@Data

public class ModuleInfoWrapper {

    private SummaryProfile summaryProfile;

    private SummaryDetail summaryDetail;

    private AssetProfile assetProfile;

    private FundProfile fundProfile;

    private Price price;

    private QuoteType quoteType;

    private EsgScores esgScores;

    private IncomeStatementHistory incomeStatementHistory;

    private IncomeStatementHistoryQuarterly incomeStatementHistoryQuarterly;

    private BalanceSheetHistory balanceSheetHistory;

    private BalanceSheetHistoryQuarterly balanceSheetHistoryQuarterly;

    private CashFlowStatementHistory cashflowStatementHistory;

    private CashFlowStatementHistoryQuarterly cashflowStatementHistoryQuarterly;

    private DefaultKeyStatistics defaultKeyStatistics;

    private FinancialData financialData;

    private CalendarEvents calendarEvents;

    private SecFilings secFilings;

    private UpgradeDowngradeHistory upgradeDowngradeHistory;

    private InstitutionOwnership institutionOwnership;

    private FundOwnership fundOwnership;

    private MajorDirectHolders majorDirectHolders;

    private MajorHoldersBreakdown majorHoldersBreakdown;

    private InsiderTransactions insiderTransactions;

    private InsiderHolders insiderHolders;

    private NetSharePurchaseActivity netSharePurchaseActivity;

    private Earnings earnings;

    private EarningsHistory earningsHistory;

    private EarningsTrend earningsTrend;

    private IndustryTrend industryTrend;

    private IndexTrend indexTrend;

    private SectorTrend sectorTrend;

    private RecommendationTrend recommendationTrend;

    private FuturesChain futuresChain;


}
